#Resource Icon, 1, "timedate.ico"
#Resource Manifest, 1, "DateEcho.exe.manifest"


#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Echo date/time to STDOut"
#Resource Version$ "LegalCopyright",   "Copyright 2002-2017 BasicAware"
#Resource Version$ "OriginalFilename", "DateEcho.exe"
#Resource Version$ "ProductName",      "DateEcho"
#Resource Version$ "ProductVersion",   "2.0.0.0"
#Resource Version$ "FileVersion",      "2.0.0.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
